name = "google-search-api-chamod"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
API_KEY = "REPLACE_WITH_YOUR_GOOGLE_API_KEY"
CX_ID = "REPLACE_WITH_YOUR_CX_ID"
CREATOR = "Chamod Nimsara"
